### ISSUE TITLE
ERROR when configuring using CMAKE

### ISSUE THREAD

**Issue by jiangleads** [NOAA-GFDL/GFDL-VortexTracker#36]
Hello, I had useing cmake configure, however  the cmake program crashed:
```

- Configuring done (5.4s)
CMake Error at src/support/CMakeLists.txt:19 (target_link_libraries):
  Target "supvit.x" links to:

    bacio::bacio_4

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

```

I had already installed the NCEPLIBS and i don't know the reason. Could anyone help to find what the problem is? Thanks in advance.

[CMakeCache.txt](https://github.com/user-attachments/files/17236278/CMakeCache.txt)
[cmake.log.txt](https://github.com/user-attachments/files/17236279/cmake.log.txt)

**Comment by jiangleads** [comment]
> 

> OK, I will take the _4 out of the name, and that will apply for the 2.5.0 release. Any users of bacio will have to change their build systems to no longer use the "_4" at the end of the library or include directory name.
> 
> We can try this out on the g2 project and get if figured out...

https://github.com/NOAA-EMC/NCEPLIBS-bacio/issues/25#issuecomment-940101882

**Comment by jiangleads** [comment]
The problems has been solved. 
change the alias "bacio::bacio_4" into "bacio::bacio"
sed -i "s/bacio_4/bacio/g" src/support/CMakeLists.txt
sed -i "s/bacio_4/bacio/g" src/tracker/CMakeLists.txt
Then rebuild the packages.

**Comment by jiangleads** [comment]
@mcallic2  Thank you for your reply.

I was built on Rocky Linux 9.4 (similar to RHEL system) with Intel compilers 2023 version. I could not built using gcc13 since some compile arguments was Intel -only which was not compatible.

As mentioned in the quoted post, earlier versions of bacio (e.g., 2.4.?) could still produce the library named bacio_4.a, which was searchable by CMake. I tried to built with spack environment, but I finally give up with the complex configuration. The installation is more sophiscated than the GFDL-VortexTracker due to the dependeny hell.

By the way, I had tried using an older version of the GFDL-VortexTracker (ver 3.9) docker container, and it worked fine. https://github.com/dtcenter/METplus/discussions/1781#discussioncomment-3601480

Since the former GFDL-VortexTracker's site on DTC has ceased maintenance, I could not access the test data or the most recent user guide. If possible, could you please be so kind as to update these resources on GitHub?

Thank you.

**Comment by mcallic2** [comment]
@jiangleads  We, as in Tim and I, do not and have not managed or maintained any of the code from that DTCcenter. Tim worked with them years back with an older version of the tracker source code and they took that code and did their own thing. The DTC website used very outdated source code from this tracker's repository but we do not have access or knowledge of other code/files that were created from the DTC community. 

I very much understand the confusion though. We are actively trying to work on this repository's outreach to the community since the code has been updated significantly since the last time it was actively maintained at DTC. It is best to use our current repository's version.

As for changing the bacio_4 in our repository, we actually have it set to that bit on purpose, and as for testing. That is why I am now working with Tim on this repository. I am in the process of building a testing suite for the tracker.

With that being said, there is a Docker image that is fairly updated by GFDL that I can point you too. Using this will solve any version/library issues you are running into. I am happy to walk you through it if you need more assistance building and running the container.
You can clone the docker image here:
`git clone -b update-docker-tracker git@github.com:mcallic2/HPC-ME.git`

**Comment by jiangleads** [comment]
@mcallic2 Thank you for the reply that introduced the background of this repository and, most importantly, showed the updated Docker image. I look forward to the completion of the testing suite. :)

**Comment by mcallic2** [comment]
@jiangleads It's my pleasure, that's what I'm here for! I am going to close this issue, but if you need any further assistance please don't hesitate to shoot me an email.
